// nwt-ng/src/app/components/header/header.component.ts
import { Component, OnInit, ViewChild, ElementRef, HostListener } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  constructor() { }

  ngOnInit() {
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="col-md-2">
    <span class="navbar-brand" href="#">
      <img alt="brand" src="../assets/icon.png" class="img-fluid" />Perfume store
    </span>
  </div>
  <div class="col-md-7"></div>
  <div class="col-md-3">
    <input class="form-control mr-sm-2" type="text" placeholder="Search">
  </div>
</nav>

// nwt-react/src/components/Header/Header.js
import React from "react";

import "./Header.css";
import logo from '../../assets/icon.png';

const header = props => (
  <nav className="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div className="col-md-2">
      <span className="navbar-brand" href="#">
        <img alt="brand" src={logo} className="img-fluid" />
        Perfume store
      </span>
    </div>
    <div className="col-md-7" />
    <div className="col-md-3">
      <input
        className="form-control mr-sm-2"
        type="text"
        placeholder="Search"
      />
    </div>
  </nav>
);

export default header;
