// nwt-react/src/components/Favorites/Favorites.js
import React from "react";

import { Link } from "react-router-dom";

const favorites = props => {
  let content = null;
  if (props.flag) {
    content = props.favPerfumes.map(el => {
      return (
        <Link key={el.id} to={"/product/" + el.id}>
          <div
            className="list-group-item list-group-item-action"
            style={{ cursor: "pointer" }}
          >
            <div className="row">
              <div className="col-md-4">
                <img
                  style={{ width: "100%" }}
                  src={el.imageUrl}
                  alt={el.name}
                />
              </div>
              <div className="col-md-8">
                <div>
                  <h6>{el.name}</h6>
                </div>
                <div>
                  <p>
                    Rating {el.rating} based on {el.users.length} reviews
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Link>
      );
    });
  } else {
    content = (
      <div className="row bg-primary text-white">
        <div className="col-md-2" />
        <div className="col-md-8">
          <h6 style={{ textAlign: "center" }}>You have no favorite perfume</h6>
        </div>
        <div className="col-md-2" />
      </div>
    );
  }
  return (
    <div className="bg-primary" style={{ padding: "20px" }}>
      <h2 className="text-white">Favorites</h2>
      <div className="list-group">{content}</div>
    </div>
  );
};

export default favorites;

// nwt-ng/src/app/components/favorites/favorites.component.ts
import { Component, OnInit } from '@angular/core';

import { Perfume } from 'src/app/models/perfume.model';
import { PerfumesService } from 'src/app/services/perfumes.service';

@Component({
  selector: 'app-favorites',
  templateUrl: './favorites.component.html',
  styleUrls: ['./favorites.component.css']
})
export class FavoritesComponent implements OnInit {
  constructor(private _perfumesService: PerfumesService) {}

  perfumes: Perfume[] = [];

  ngOnInit() {
    this.perfumes = this._perfumesService.getFavorites();
  }
}

<div class="bg-primary" style="padding:20px">
  <h2 class="text-white">Favorites</h2>
</div>
<div class="list-group">
  <div
    *ngFor="let perfume of perfumes"
    class="list-group-item list-group-item-action"
    [routerLink]="['/product', perfume.id]"
  >
    <div class="row">
      <div class="col-md-4">
        <img style="width:100%" [src]="perfume.imageUrl" [alt]="perfume.name" />
      </div>
      <div class="col-md-8">
        <div>
          <h6>{{ perfume.name }}</h6>
        </div>
        <div>
          <p>
            Rating {{ perfume.rating }} based on
            {{ perfume.users.length }} reviews
          </p>
        </div>
      </div>
    </div>
  </div>
  <div *ngIf="perfumes.length === 0">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <h6 style="text-align: center">You have no favorite perfume</h6>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>
